sudo: required
language: node_js

node_js:
  - "4"
os:
  - linux
  - osx

before_script:
  - npm i -g npm
  - npm config set spin false
  - npm config set progress false
  
  - npm link

script:
  - pwd
  - cd ..
  - pwd
  - ngg new testProj
  
  - cd testProj
  
  - ngg generate component myComp
  - ngg g pipe my-pipe
  - ngg build -prod
